[platformio]
default_envs = featheresp32

[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_ldf_mode = deep+
lib_extra_dirs = lib

lib_deps =
    tzapu/WiFiManager
    knolleary/PubSubClient
    bblanchon/ArduinoJson
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BME680 Library
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit ADS1X15
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    adafruit/Adafruit SH110X
    arduino-libraries/Ethernet

build_flags =
    -DCORE_DEBUG_LEVEL=0
